Municipio.create!([
  {name: "Monterrey", montoTotal: 1.0},
  {name: "Guadalupe", montoTotal: 133209.0},
  {name: "Apodaca", montoTotal: 189483.0},
  {name: "San Nicolás de las Garza", montoTotal: 2483414.0},
  {name: "Escobedo", montoTotal: 4758934.0},
  {name: "Santa Catarina", montoTotal: 498630.0},
  {name: "Juárez", montoTotal: 83093528.0},
  {name: "García", montoTotal: 39485340.0},
  {name: "San Pedro Garza García", montoTotal: 395820.0},
  {name: "Cadereyta", montoTotal: 8298843273.0},
  {name: "Santiago", montoTotal: 427502458.0},
  {name: "Salinas Victoria", montoTotal: 324958.0}
])
Obra.create!([
  {name: "Centro Cultural y Deportivo del Valle", monto: 3480234.34, status: "Terminado", avance: 100, tipo: "Construcción", municipio_id: 1, participantes: nil},
  {name: "Pavimento, Alfonso Reyes entre Jiménez y Neil Armstrong", monto: 31359345.32, status: "En Proceso", avance: 3, tipo: "Pavimentación", municipio_id: 1, participantes: nil},
  {name: "Remodelación de oficinas en la dirección de adquisiciones", monto: 257938.51, status: "Terminado", avance: 100, tipo: nil, municipio_id: nil, participantes: nil},
  {name: "ESTUDIO DE GEOTECNIA Y DISEÑO DE PAVIMENTOS EN DIVERSOS PUNTOS DENTRO DEL MUNICIPIO DE SAN PEDRO GARZA GARCIA, N.L.", monto: 273702.0, status: "Terminado", avance: 100, tipo: "Remodelación", municipio_id: 9, participantes: 1},
  {name: "REUBICACIÓN DE COLECTOR SANITARIO SUR AV. MORONES PRIETO", monto: 224645.0, status: "Terminado", avance: 100, tipo: "Reubicación", municipio_id: 9, participantes: 1},
  {name: "REHABILITACIÓN DE PAVIMENTO AV. EMILIANO ZAPATA DE PLATINO A FLORES MAGÓN", monto: 920642.1, status: "Terminado", avance: 9, tipo: "Rehabilitación", municipio_id: 9, participantes: 5},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE TEOCALLI ENTRE UXMAL Y AV. SAN ÁNGEL COL. VALLE DE SAN ÁNGEL", monto: 1600294.75, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO RÍO TAMAZUNCHALE DE CALZADA DEL VALLE A VÍA ASINARA", monto: 2247408.05, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO DE AV. HUMBERTO LOBO DE CALZADA DEL VALLE A VASCONCELOS", monto: 3125344.53, status: "En Proceso", avance: nil, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE PROLONGACIÓN RIOLITA DE RIOLITA A TUNGSTENO", monto: 479731.8, status: "Terminada", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE JAZMÍN, CALLE BUGAMBILIA, CALLE LIRIOS EN LA COLONIA COLORINES", monto: 2118225.69, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE 5 DE MAYO ENTRE PADRE MIER Y GUERRERO", monto: 2192399.32, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO CRUCERO DE AV. ROBERTO GARZA SADA Y AV. JERÓNIMO SILLER", monto: 1098179.09, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE RÍO ORINOCO ENTRE RÍO GRIJALVA Y RÍO TAMAZUNCHALE", monto: 1961742.17, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE UXMAL ENTRE AV. SAN ÁNGEL Y MONTPARNASSE COL. VALLE DE SAN ÁNGEL", monto: 3000025.55, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO EN CALLES LAS TORRES EN LA COLONIA SAN PEDRO 400", monto: 3646004.98, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 4},
  {name: "REHABILITACIÓN DE PAVIMENTO AV. ALFONSO REYES ENTRE JIMENEZ Y NEIL ARMSTRONG", monto: 11151536.98, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 9},
  {name: "REHABILITACIÓN DE PAVIMENTO AV. VASCONCELOS DE AV. GOMEZ MORÍN A AV. LÁZARO CÁRDENAS", monto: 18589467.61, status: "Terminado", avance: 100, tipo: "Rehabilitiación", municipio_id: 9, participantes: 6},
  {name: "REHABILITACIÓN DE PAVIMENTO AV. BOSQUES DEL VALLE DE AUSTRIA A AV. ROBERTO GARZA SADA", monto: 10969899.22, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 5},
  {name: "REHABILITACIÓN DE PAVIMENTO RÍO MISSISSIPPI DE CALZADA SAN PEDRO A AV. GÓMEZ MORÍN", monto: 3889010.83, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 5},
  {name: "REHABILITACIÓN DE CANCHA DE FUTBOL EN LA CALLE FRANCISCO I. MADERO", monto: 1180790.33, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE CANCHA DE FUTBOL EN LA CALLE PASEO OLGA Y PASEO IRMA", monto: 2045282.36, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 2, participantes: 2},
  {name: "RECUBRIMIENTO DE TARTÁN EN CALZADA DEL VALLE Y CALZADA SAN PEDRO", monto: 4707508.38, status: "Terminado", avance: 100, tipo: "Recubrimiento", municipio_id: 9, participantes: 5},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE ROBLE DE LA AV. GÓMEZ MORÍN A LA AV. RICARDO MARGAIN", monto: 2565303.18, status: "Terminado", avance: 100, tipo: "Rehabilitación", municipio_id: 9, participantes: 3},
  {name: "INGENIERIA EN PUENTE CAMINO A CHIPINQUE A 30 MTS. ANTES DE LA ENTRADA A LA JOYA DE LA CORONA", monto: 138040.01, status: "Terminado", avance: 100, tipo: "Ingeniería", municipio_id: 9, participantes: 3},
  {name: "CONSTRUCCIÓN DE PAVIMENTO CALLE PROLONGACIÓN COAHUILA Y CAMINO AL TANQUE DE AGUA EN LA COLONIA CANTERAS", monto: 3819492.79, status: "En Proceso", avance: 100, tipo: "Construcción", municipio_id: 9, participantes: 2},
  {name: "PROYECTO EJECUTIVO GAZA VASCONCELOS Y LÁZARO GARZA AYALA", monto: 2097556.15, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 5},
  {name: "PROYECTO DE REGENERACIÓN DE ESPACIOS PÚBLICOS AV. ALFONSO REYES Y CALLE PUEBLA", monto: 174000.01, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 1},
  {name: "CONSTRUCCIÓN DE CANAL PLUVIAL EN LA CALLE UXMAL Y CALLE TAJIN, EN LA COLONIA VALLE DE SAN ÁNGEL", monto: 280390.97, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 1},
  {name: "REHABILITACIÓN DE VITAPISTA EN LA CALLE ARQUÍMIDES Y SÓCRATES EN LA COLONIA RESIDENCIAL CHIPINQUE 2DO. Y 3ER. SECTOR", monto: 441763.24, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 4},
  {name: "PROYECTO EJECUTIVO PASO DEPRIMIDO REAL SAN AGUSTÍN Y ALFONSO REYES", monto: 2090054.09, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 5},
  {name: "REHABILITACIÓN DE PAVIMENTO CALLE MANGANESO, CALLE FIERRO, CALLE PLATINO, CALLE POTASIO Y CALLE FLÚOR EN LA COL. SAN PEDRO 400", monto: 3500217.11, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO PRIVADA JORDÁN DE CALZADA DEL VALLE A CALLEJÓN DE CAPELLANÍA", monto: 619797.86, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "AMPLIACIÓN DE LA AV. ALFONSO REYES (4TA. ETAPA) CUERPO SUR DE LA PRIV. DIEGO DE MONTEMAYOR A LA CALLE MATAMOROS", monto: 2961348.84, status: "Terminado", avance: 100, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "Remodelacion de oficinas en la dirección de adquisiciones", monto: 257938.51, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de oficinas de atención integral para la violencia familiar", monto: 1730127.07, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Contrucción de biblioteca y kiosko cibernetico en la col. Martires de cananea", monto: 404566.25, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Contrucción de caseta para guardias en el exterior de la torre administrativa", monto: 233814.56, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de drenaje pluvial en calle charro entre herradura y corral Col. los portales", monto: 1299304.21, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de banquetas de concreto en la calle Margarito Rodriguez y Eugenio Garza Sada Col. la fortaleza", monto: 441280.21, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de bodega en DIF municipal", monto: 695626.17, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Rehabilitación de pavimento asfaltico en la calle Tenochtitlan entre av. Palermo y av.Clouthier col. rincon de las mitras", monto: 2098781.21, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Introducción de red de drenaje sanitario en calle Mitla y Xolotl entre coalicue y coatl col, fama II", monto: 673214.32, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Remodelación de oficinas de la dirección de la secretaría de administración y finanzas", monto: 297645.19, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Pavimentación de concreto hidraulico en calle sierra picachos Col. Infonavit Lomas de Santa Catarina", monto: 3478799.64, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Pavimentación con carpeta asfaltica en calle Urano col. Puerta del Sol", monto: 2734934.11, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Rehabilitación de pavimento asfaltico en calle pilastra arcada col. Inf. Cuauhtemoc Ind. unidad nacional", monto: 3509246.05, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Introducción de red de drenaje sanitario en calle calientre cromo y manuel col. fama II", monto: 536181.79, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de pavimento asfaltico calle Ignacio Perez Col. Hacienda Santa Catarina", monto: 532277.91, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Reconstrucción de pavimento asfaltico calle secundaria entre sierra caliza y sierra San Cristobal Col. Infonavit Lomas de Santa Catarina", monto: 1094420.62, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de espacio deportivo en calle palo verde y carrizo Col. mirador de las mitras", monto: 9969243.59, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de red de alumbrado Público en ave. Manuel J. Clouthier", monto: 1507572.37, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de red de alumbrado público en marruecos col.Fama II y arboledas de las mitras", monto: 1150906.85, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de red de alumbrado público en calle 1a. avenida Col. Santa Martha", monto: 1120084.54, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Rehabilitación de área recreativa ubicado en ave. fortaleza col. Nueva fortaleza", monto: 123994.54, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Rehabilitación de pavimento asfaltico calle Urano Col. Puerta del sol", monto: 2556618.27, status: nil, avance: nil, tipo: nil, municipio_id: nil, participantes: nil},
  {name: "Rehabilitación de pavimento con concreto hidraulico calle bahia de la paz col San Gilberto", monto: 1942394.82, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción del muro de contención y pavimento de concreto hidraulico calle bahia de la paz cruz Col. San Gilberto", monto: 704478.92, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de muro de contención y pavimento de concreto hidraulico en calle perimetral sur cruz Col. San Gilberto", monto: 714054.04, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción del espacio deportivo calle valle de la montaña col. Real del valle", monto: 8395226.58, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "Construcción de espacio deportivo calle Madrid y Pamplona Col. puerta de las mitras", monto: 9974713.15, status: nil, avance: nil, tipo: nil, municipio_id: 6, participantes: nil},
  {name: "DISEÑO EN MUROS DE CONTENCIÓN Y ESTABILIDAD DE TALUDES COL. VALLE DE SAN ÁNGEL, SAN PEDRO GARZA GARCÍA, N.L.", monto: 297159.52, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 2},
  {name: "CONSTRUCCIÓN DE PUENTES PEATONALES CALLE JIMENEZ-MARÍA CANTÚ SOBRE EL RÍO SANTA CATARINA", monto: 42250032.61, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 6},
  {name: "INFRAESTRUCTURA PARA LA MOVILIDAD ALTERNATIVA EN CALLE JIMENEZ DE ALFONSO REYES A 16 DE SEPTIEMBRE", monto: 7139812.53, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 10},
  {name: "CONSTRUCCIÓN DE ANDADOR ALTERNATIVO (TRAMO 1) EN AV. ALFONSO REYES DE UDEM A REAL SAN AGUSTÍN", monto: 8468875.41, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 9},
  {name: "CONSTRUCCIÓN DE DRENAJE PLUVIAL AV. JIMENEZ DE GALEANA A L AV. VASCONCELOS, SAN PEDRO GARZA GARCÍA, N.L.", monto: 4299355.85, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "INFRAESTRUCTURA PARA LA MOVILIDAD ALTERNATIVA EN AV. HUMBERTO LOBO DE VASCONCELOS A RÍO GUADALQUIVIR", monto: 2539823.02, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "REHABILITACIÓN DE PAVIMENTO AV. RICARDO MARGAIN DE VASCONCELOS A LA AV. LÁZARO CÁRDENAS ", monto: 5390014.89, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 7},
  {name: "REHABILITACIÓN DE PAVIMENTO AV. LÁZARO CÁRDENAS ENTRE DIEGO RIVERA Y RUFINO TAMAYO", monto: 5150130.83, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 7},
  {name: "SUMINISTRO Y COLOCACIÓN DE CALDERA PARA ALBERCA SEMIOLIMPICA EN EL GIMNASIO LÁZARO GARZA AYALA", monto: 853943.89, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 5},
  {name: "REHABILITACIÓN DE CANCHA (ELPOZO) 1RA. ETAPA CALLE AZUFRE ENTRE ALUMINIO Y URANIO EN LA COLONIA SAN PEDRO 400", monto: 1928424.62, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "CONSTRUCCIÓN DE PALAPA EN PARQUE EN CALLE 21 DE MARZO, COL. BARRANCAS DEL PEDREGA", monto: 78064.76, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 2},
  {name: "REHABILITACIÓN DE CAMERINOS AUDITORIO SAN PEDRO", monto: 870090.52, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 3},
  {name: "ALUMBRADO PÚBLICO EN ESPACIO DEPORTIVO CALLE AZUFRE ENTRE ALUMINIO Y URANIO", monto: 248994.92, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 1},
  {name: "CONSTRUCCIÓN DE ANDADOR ALTERNATIVO (TRAMO 3) RÍO SUCHIATE DE LA AV. MORONES PRIETO A LA AV. ALFONSO REYES", monto: 2529887.7, status: nil, avance: nil, tipo: nil, municipio_id: 9, participantes: 3}
])
Provider.create!([
  {nombre: "MaizMier", ganancias: 249328598.0, totalObras: 25},
  {nombre: "Consorcio Constructivo y Proyectos, SA DE CV", ganancias: 501317.2, totalObras: 2}
])
